# Feito com Muito S2 e Muito Caf√© :)
version: "3.8"

services:
  shortb-db:
    image: postgres:15
    container_name: shortb-db
    restart: always
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: dba
      POSTGRES_DB: ShortDB
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - shortb_db_data:/var/lib/postgresql/data

  shortb-adminer:
    image: adminer
    container_name: shortb-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - shortb-db

  shortb-api:
    image: beyondtest/shortb-api:beta
    container_name: shortb-api
    restart: always
    environment:
      PORT: 3333
      DATABASE_URL: postgres://dba:dba@shortb-db:5432/ShortDB?sslmode=disable
      JWT_SECRET: vaiplaneta
    ports:
      - "3333:3333"
    depends_on:
      - shortb-db

  shortb-web:
    image: beyondtest/shortb-web:latest
    container_name: shortb-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - shortb-api

volumes:
  shortb_db_data:
